version: "3.9"
services:
  adguard:
    image: adguard/adguardhome
    restart: always
    # build: .
    ports:
      - "3000:3000/tcp"
      - "80:80/tcp"
      - "53:53/udp"
    volumes:
      - ./adguard-conf:/opt/adguardhome/conf
      - ./adguard-data:/opt/adguardhome/data
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto-conf:/mosquitto/config
    ports:
      - "1883:1883/tcp"
  middleware:
    build: ./middleware/
    restart: always
    depends_on:
      - mosquitto
      - adguard
